{{- if .Values.adapters.lora.enabled }}
{{- $args := dict "dot" . "component" "adapter-lora-vertx" "name" "adapter-lora-vertx-conf" -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.adapters.lora.hono.app.maxInstances }}
      lora:
        {{- if .Values.adapters.lora.hono.lora }}
        {{- .Values.adapters.lora.hono.lora | toYaml | nindent 8 }}
        {{- else }}
        bindAddress: "0.0.0.0"
        keyPath: "/etc/hono/key.pem"
        certPath: "/etc/hono/cert.pem"
        insecurePortEnabled: true
        insecurePortBindAddress: "0.0.0.0"
        {{- end }}
      {{- include "hono.healthServerConfig" .Values.adapters.lora.hono.healthCheck | nindent 6 }}
      {{- include "hono.serviceClientConfig" $args | nindent 6 }}
{{- if not .Values.adapters.lora.extraSecretMounts }}
data:
  key.pem: {{ .Files.Get "hono-demo-certs-jar/lora-adapter-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "hono-demo-certs-jar/lora-adapter-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
  adapter.credentials: {{ .Files.Get "example/lora-adapter.credentials" | b64enc }}
{{- end }}
{{- end }}
