{{- if and (eq .Values.platform "openshift") .Values.adapters.lora.enabled }}
{{- $args := dict "dot" . "component" "adapter-lora-vertx" "name" "adapter-lora-vertx-sec" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .Release.Name }}-adapter-lora-vertx
{{- end }}
