{{- if .Values.jaegerBackendExample.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "tracing" "name" "jaeger-collector" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  ports:
  - name: jaeger-collector-tchannel
    port: 14267
    protocol: TCP
    targetPort: 14267
  - name: jaeger-collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
  type: ClusterIP
{{- end }}
