{{- if .Values.jaegerBackendExample.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- $args := dict "dot" . "component" "tracing" "name" "jaeger-query" }}
  {{- include "hono.metadata" $args | nindent 2 }}
  {{- with .Values.jaegerBackendExample.svc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: query-http
      port: 80
      protocol: TCP
      targetPort: 16686
  selector:
    {{- include "hono.matchLabels" $args | nindent 4 }}
{{- if and ( eq .Values.useLoadBalancer true ) ( ne .Values.platform "openshift" ) }}
  type: LoadBalancer
{{- else }}
  type: NodePort
{{- end }}
{{- with .Values.jaegerBackendExample.svc.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
{{- end }}
{{- end }}
