{{- if .Values.deviceRegistryExample.enabled }}
{{- $args := dict "dot" . "component" "service-device-registry" "name" "service-device-registry" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.deviceRegistryExample.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: 1Mi
{{- end }}
