{{- $args := dict "dot" . "component" "service-auth" "name" "service-auth" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
    spec:
      containers:
      - image: {{ .Values.authServer.imageName }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-service-auth
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: amqps
          containerPort: 5671
          protocol: TCP
        - name: amqp
          containerPort: 5672
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: authentication-impl,dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        - name: _JAVA_OPTIONS
          value: "{{ .Values.defaultJavaOptions }}"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        {{- include "hono.container.secretVolumeMounts" ( dict "name" $args.name "conf" .Values.authServer ) | indent 8 }}
        resources:
          limits:
            memory: "196Mi"
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 10
      volumes:
      {{- include "hono.pod.secretVolumes" ( dict "releaseName" .Release.Name "name" $args.name "conf" .Values.authServer ) | indent 6 }}
