{{- if eq .Values.platform "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  {{- $args := dict "dot" . "component" "service-auth" "name" "service-auth" }}
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  port:
    targetPort: amqps
  tls:
    termination: passthrough
  to:
    kind: Service
    name: {{ .Release.Name }}-service-auth
{{- end }}
