{{- if .Values.adapters.kura.enabled }}
{{- $args := dict "dot" . "component" "adapter-kura" "name" "adapter-kura-conf" -}}
apiVersion: v1
kind: Secret
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
type: Opaque
stringData:
  application.yml: |
    hono:
      app:
        maxInstances: {{ .Values.adapters.kura.hono.app.maxInstances }}
      kura:
        {{- if .Values.adapters.kura.hono.kura }}
        {{- .Values.adapters.kura.hono.kura | toYaml | nindent 8 }}
        {{- else }}
        bindAddress: 0.0.0.0
        insecurePortBindAddress: 0.0.0.0
        insecurePortEnabled: true
        keyPath: /etc/hono/key.pem
        certPath: /etc/hono/cert.pem
        tenantIdleTimeout: {{ .Values.adapters.defaultTenantIdleTimeout | quote }}
        {{- end }}
      {{- include "hono.healthServerConfig" .Values.adapters.kura.hono.healthCheck | nindent 6 }}
      {{- include "hono.serviceClientConfig" $args | nindent 6 }}
{{- if not .Values.adapters.kura.extraSecretMounts }}
data:
  key.pem: {{ .Files.Get "hono-demo-certs-jar/kura-adapter-key.pem" | b64enc }}
  cert.pem: {{ .Files.Get "hono-demo-certs-jar/kura-adapter-cert.pem" | b64enc }}
  trusted-certs.pem: {{ .Files.Get "hono-demo-certs-jar/trusted-certs.pem" | b64enc }}
  adapter.credentials: {{ .Files.Get "example/kura-adapter.credentials" | b64enc }}
{{- end }}
{{ end }}
