{{- if .Values.adapters.kura.enabled }}
{{- $args := dict "dot" . "component" "adapter-kura" "name" "adapter-kura" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- include "hono.metadata" $args | nindent 2 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hono.matchLabels" $args | nindent 6 }}
  template:
    metadata:
      {{- include "hono.metadata" $args | nindent 6 }}
    spec:
      containers:
      {{- include "hono.jaeger.agent" . | indent 6 }}
      - image: {{ .Values.adapters.kura.imageName }}
        imagePullPolicy: IfNotPresent
        name: eclipse-hono-adapter-kura
        ports:
        - name: health
          containerPort: {{ .Values.healthCheckPort }}
          protocol: TCP
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        - name: secure-mqtt
          containerPort: 8883
          protocol: TCP
        securityContext:
          privileged: false
        env:
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/hono/
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        - name: LOGGING_CONFIG
          value: classpath:logback-spring.xml
        - name: _JAVA_OPTIONS
          value: "{{ .Values.defaultJavaOptions }}"
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        {{- include "hono.jaeger.clientConf" $args | indent 8 }}
        volumeMounts:
        {{- include "hono.container.secretVolumeMounts" ( dict "name" $args.name "conf" .Values.adapters.kura ) | indent 8 }}
        resources:
          limits:
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ .Values.healthCheckPort }}
            scheme: HTTPS
          initialDelaySeconds: 180
      volumes:
      {{- include "hono.pod.secretVolumes" ( dict "releaseName" .Release.Name "name" $args.name "conf" .Values.adapters.kura ) | indent 6 }}
{{ end }}
